name: "commit-obs"

on:
  push:
    branches: 
    - 'obs'
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check Out 
      uses: actions/checkout@v2
    #安装JDK1.8
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8

    # 完成java项目打包
    - name: build maven project
      run: mvn clean -U package -Dmaven.test.skip 

    # jar包比较大，先上传到OBS
    - name: Upload To Huawei OBS
      uses: huaweicloud/obs-helper@v1.0.0
      id: upload_file_to_obs
      with:
        access_key: ${{ secrets.ACCESSKEY }}
        secret_key: ${{ secrets.SECRETACCESSKEY }}
        region: cn-north-4
        bucket_name: hdn-github-action
        operation_type: upload
        local_file_path: target/functionj.jar
        obs_file_path: function/functionj/v1/    

    #通过OBS部署函数
    - name: deploy OBS function file to huaweicloud functiongraph
      uses: huaweicloud/functiongraph-deploy-action@v1.0
      with:
        ak: ${{ secrets.ACCESSKEY }}
        sk: ${{ secrets.SECRETACCESSKEY }}
        endpoint: functiongraph.cn-north-4.myhuaweicloud.com
        project_id: 0dd8cb413000906a2fcdc019b5a84546
        function_codetype: obs
        function_urn: urn:fss:cn-north-4:0dd8cb413000906a2fcdc019b5a84546:function:default:func_bpPpfMkw:latest
        function_file: https://bucket-test.${obs-endpoint}/function/functionj/v1/functionj.jar
